--Drop existing indexes
DROP INDEX IDX_EMPLOYEE_SSNUM;
DROP INDEX IDX_EMPLOYEE_NAME;
DROP INDEX IDX_EMPLOYEE_MANAGER;
DROP INDEX IDX_EMPLOYEE_DEPT;
DROP INDEX IDX_EMPLOYEE_SALARY;
DROP INDEX IDX_EMPLOYEE_FRIENDS;

CREATE INDEX IDX_EMPLOYEE_SSNUM ON EMPLOYEE (SSNUM);
CREATE INDEX IDX_EMPLOYEE_NAME ON EMPLOYEE (NAME);
CREATE INDEX IDX_EMPLOYEE_MANAGER ON EMPLOYEE (MANAGER);
CREATE INDEX IDX_EMPLOYEE_DEPT ON EMPLOYEE (DEPT);
CREATE INDEX IDX_EMPLOYEE_SALARY ON EMPLOYEE (SALARY);
CREATE INDEX IDX_EMPLOYEE_FRIENDS ON EMPLOYEE (NUMFRIENDS);

CLUSTER EMPLOYEE USING IDX_EMPLOYEE_SSNUM;